#!/usr/bin/env python
import script.output as output
import script.target as target

libprpc = target.lib(
    "libprpc",
    srcs = [
        target.re2c( "src/prpc/lex.re.c" ),
        "src/prpc/parse.c",
        "src/prpc/msg.c",
        "src/prpc/cmds.c"
    ]
)

libmain = target.lib(
    "libmain",
    srcs = [
        "src/sys/ansiterm.c",
        "src/sys/log.c",
        target.re2c("src/cmds.re.c")
    ],
    incdirs = [ "src" ]
)

app = target.executable(
    "app",
    srcs = [
        "src/app.c",
        "src/main.c"
    ],
    incdirs = [ "src" ],
    objs    = [ libmain, libprpc ],
    aliases = [ "app" ]
)

libtest = target.lib(
    "libtest",
    srcs = [
        "tests/lib/test.c"
    ],

    incdirs = [
        "src"
    ],

    objs = [ libmain ]
)

def add_test( name ):
    return target.executable(
        "tests/%s" % name,
        srcs    = [ "tests/%s.c" % name ],
        incdirs = ["src", "tests/lib"],
        objs=[libprpc, libmain, libtest]
    )

tests = [
    add_test("parse"),
    add_test("lex"),
    add_test("msg")
]

with open( "targets/autogen.ninja", "w" ) as fhandle:
    output.rules( fhandle, [app] + tests )

# MODIFIED
