/* Generated by re2c 1.1.1 on Thu Jul 18 23:38:13 2019 */
#line 1 "src/cmds.re.c"
#include "cmds.h"
#include <stdio.h>
#include <prpc/lex.h>
#include <prpc/msg.h>
#include <sys/log.h>

PRPC_Parse_Function_t prpc_cmd_parser_get( const char **ptr );
PRPC_CMD( has )
{
    const char *name_begin, *name_end;
    PRPC_Status_t stat = prpc_cmd_parse_args( ptr, id, 1, TOKEN_IDENTIFIER, &name_begin, &name_end );
    if( stat.status == PRPC_OK ) {
        log_verbose(">> Looking for %.*s", name_end-name_begin, name_begin);
        PRPC_Parse_Function_t cmd = prpc_cmd_parser_get(&name_begin);
        prpc_build_result_boolean( resp_buf, max_resp_len, id, cmd != NULL );
    }
    else prpc_build_error_status( resp_buf, max_resp_len, id, stat );
}

PRPC_CMD( hello )
{
    printf("Hello world !\n");
    prpc_build_ok( resp_buf, max_resp_len, id );
}

PRPC_CMD( funky )
{
    printf("YEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
    prpc_build_result( resp_buf, max_resp_len, id, 4, PRPC_INT, 1203, PRPC_BOOLEAN, 1, PRPC_STRING, "ARGH", PRPC_IDENTIFIER, "OOOH" );
}

PRPC_CMD( replicate )
{
    int        intg;
    float       num;
    uint8_t boolean;

    PRPC_Status_t stat = prpc_cmd_parse_args( ptr, id, 3,
        PRPC_INT, &intg,
        PRPC_FLOAT, &num,
        PRPC_BOOLEAN, &boolean
    );

    if( stat.status == PRPC_OK ) {
        prpc_build_result( resp_buf, max_resp_len, id, 3, PRPC_INT, intg, PRPC_FLOAT, num, PRPC_BOOLEAN, boolean );
    }

    else prpc_build_error_status( resp_buf, max_resp_len, id, stat );
}

PRPC_Parse_Function_t prpc_cmd_parser_get( const char **ptr )
{
    const char *YYMARKER;

    
#line 59 "src/cmds.c"
{
	char yych;
	yych = *(*ptr);
	switch (yych) {
	case 'F':
	case 'f':	goto yy4;
	case 'H':
	case 'h':	goto yy5;
	case 'R':
	case 'r':	goto yy6;
	default:	goto yy2;
	}
yy2:
	++(*ptr);
yy3:
#line 60 "src/cmds.re.c"
	{ return NULL;           }
#line 77 "src/cmds.c"
yy4:
	yych = *(YYMARKER = ++(*ptr));
	switch (yych) {
	case 'U':
	case 'u':	goto yy7;
	default:	goto yy3;
	}
yy5:
	yych = *(YYMARKER = ++(*ptr));
	switch (yych) {
	case 'A':
	case 'a':	goto yy9;
	case 'E':
	case 'e':	goto yy10;
	default:	goto yy3;
	}
yy6:
	yych = *(YYMARKER = ++(*ptr));
	switch (yych) {
	case 'E':
	case 'e':	goto yy11;
	default:	goto yy3;
	}
yy7:
	yych = *++(*ptr);
	switch (yych) {
	case 'N':
	case 'n':	goto yy12;
	default:	goto yy8;
	}
yy8:
	(*ptr) = YYMARKER;
	goto yy3;
yy9:
	yych = *++(*ptr);
	switch (yych) {
	case 'S':
	case 's':	goto yy13;
	default:	goto yy8;
	}
yy10:
	yych = *++(*ptr);
	switch (yych) {
	case 'L':
	case 'l':	goto yy15;
	default:	goto yy8;
	}
yy11:
	yych = *++(*ptr);
	switch (yych) {
	case 'P':
	case 'p':	goto yy16;
	default:	goto yy8;
	}
yy12:
	yych = *++(*ptr);
	switch (yych) {
	case 'K':
	case 'k':	goto yy17;
	default:	goto yy8;
	}
yy13:
	++(*ptr);
#line 61 "src/cmds.re.c"
	{ return prpc_cmd_has;   }
#line 143 "src/cmds.c"
yy15:
	yych = *++(*ptr);
	switch (yych) {
	case 'L':
	case 'l':	goto yy18;
	default:	goto yy8;
	}
yy16:
	yych = *++(*ptr);
	switch (yych) {
	case 'L':
	case 'l':	goto yy19;
	default:	goto yy8;
	}
yy17:
	yych = *++(*ptr);
	switch (yych) {
	case 'Y':
	case 'y':	goto yy20;
	default:	goto yy8;
	}
yy18:
	yych = *++(*ptr);
	switch (yych) {
	case 'O':
	case 'o':	goto yy22;
	default:	goto yy8;
	}
yy19:
	yych = *++(*ptr);
	switch (yych) {
	case 'I':
	case 'i':	goto yy24;
	default:	goto yy8;
	}
yy20:
	++(*ptr);
#line 63 "src/cmds.re.c"
	{ return prpc_cmd_funky; }
#line 183 "src/cmds.c"
yy22:
	++(*ptr);
#line 62 "src/cmds.re.c"
	{ return prpc_cmd_hello; }
#line 188 "src/cmds.c"
yy24:
	yych = *++(*ptr);
	switch (yych) {
	case 'C':
	case 'c':	goto yy25;
	default:	goto yy8;
	}
yy25:
	yych = *++(*ptr);
	switch (yych) {
	case 'A':
	case 'a':	goto yy26;
	default:	goto yy8;
	}
yy26:
	yych = *++(*ptr);
	switch (yych) {
	case 'T':
	case 't':	goto yy27;
	default:	goto yy8;
	}
yy27:
	yych = *++(*ptr);
	switch (yych) {
	case 'E':
	case 'e':	goto yy28;
	default:	goto yy8;
	}
yy28:
	++(*ptr);
#line 64 "src/cmds.re.c"
	{ return prpc_cmd_replicate; }
#line 221 "src/cmds.c"
}
#line 65 "src/cmds.re.c"

}

void process_cmd( char *resp, const size_t max_len, const PRPC_ID_t id, const char *name, const char **ptr )
{
    PRPC_Parse_Function_t cmd = prpc_cmd_parser_get(&name);
    if( cmd != NULL ) {
        cmd( ptr, resp, max_len, id );
    }

    else {
        prpc_build_error( resp, max_len, id, "Uknown method" );
    }
}

void cmds_init()
{
    prpc_process_callback_register( process_cmd, NULL );
}
