/* Generated by re2c 1.1.1 on Mon Jul  8 22:23:39 2019 */
#line 1 "src/lex.re.c"
#include "lex.h"
#include "parse.h"

#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>

const char *token_type_str( Token_Type_t type )
{
    static const char *token_str[] = {
        "TOKEN_ERROR",
        "TOKEN_EOL",
        "TOKEN_EOF",
        "TOKEN_SEPARATOR",

        "TOKEN_STRING",
        "TOKEN_INT",
        "TOKEN_FLOAT",
        "TOKEN_BOOLEAN",
        "TOKEN_IDENTIFIER",
        "TOKEN_COMMAND"
    };

    return token_str[type];
}

//////////////////////////////////////////
// Main lexer thing
//////////////////////////////////////////
char *token_next( char *start, Token_t *dst )
{
    char *YYMARKER;
    char *YYCURSOR = start;

    const char *id, *sep, *name;

    dst->begin = NULL;
    dst->end   = NULL;

    const char *yyt1;const char *yyt2;
    
#line 45 "src/lex.c"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case ' ':	goto yy6;
	case '"':	goto yy9;
	case '-':
		yyt1 = YYCURSOR;
		goto yy10;
	case '.':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'z':	goto yy12;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy14;
	case 'N':
	case 'n':	goto yy17;
	case 'Y':
	case 'y':	goto yy18;
	case '[':	goto yy19;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 68 "src/lex.re.c"
	{ dst->type = TOKEN_EOF;       return YYCURSOR; }
#line 131 "src/lex.c"
yy4:
	++YYCURSOR;
yy5:
#line 67 "src/lex.re.c"
	{ dst->type = TOKEN_ERROR;     return YYCURSOR; }
#line 137 "src/lex.c"
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 70 "src/lex.re.c"
	{ dst->type = TOKEN_SEPARATOR; return YYCURSOR; }
#line 148 "src/lex.c"
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy5;
	default:	goto yy21;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy14;
	default:	goto yy13;
	}
yy11:
#line 121 "src/lex.re.c"
	{
            dst->type  = TOKEN_IDENTIFIER;
            dst->begin = start;
            dst->end   = YYCURSOR;

            return YYCURSOR;
        }
#line 181 "src/lex.c"
yy12:
	yych = *++YYCURSOR;
yy13:
	switch (yych) {
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy12;
	default:	goto yy11;
	}
yy14:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '-':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy12;
	case '.':	goto yy26;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy14;
	case ':':	goto yy27;
	default:	goto yy16;
	}
yy16:
#line 82 "src/lex.re.c"
	{
            dst->type      = TOKEN_INT;
            dst->begin     = start;
            dst->end       = YYCURSOR;
            dst->data.intg = parse_int( dst->begin, dst->end );

            return YYCURSOR;
        }
#line 335 "src/lex.c"
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy28;
	default:	goto yy13;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy30;
	default:	goto yy13;
	}
yy19:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\r':	goto yy31;
	default:	goto yy5;
	}
yy20:
	yych = *++YYCURSOR;
yy21:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy22;
	case '"':	goto yy23;
	default:	goto yy20;
	}
yy22:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy16;
	default:	goto yy25;
	}
yy23:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy25;
	case '"':	goto yy23;
	default:	goto yy20;
	}
yy25:
#line 57 "src/lex.re.c"
	{
            dst->type           = TOKEN_STRING;
            dst->begin          = start;
            dst->end            = YYCURSOR;
            dst->data.str.begin = start+1;
            dst->data.str.end   = YYCURSOR-1;

            return YYCURSOR;
        }
#line 393 "src/lex.c"
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	default:	goto yy13;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt2 = YYCURSOR;
		goto yy35;
	default:	goto yy22;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy12;
	default:	goto yy29;
	}
yy29:
#line 100 "src/lex.re.c"
	{
            dst->type         = TOKEN_BOOLEAN;
            dst->begin        = start;
            dst->end          = YYCURSOR;
            dst->data.boolean = 0;

            return YYCURSOR;
        }
#line 561 "src/lex.c"
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy38;
	default:	goto yy13;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy40;
	default:	goto yy22;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':
	case '.':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy12;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	default:	goto yy34;
	}
yy34:
#line 72 "src/lex.re.c"
	{
            dst->type     = TOKEN_FLOAT;
            dst->begin    = start;
            dst->end      = YYCURSOR;

            dst->data.num = parse_float( dst->begin, dst->end );

            return YYCURSOR;
        }
#line 656 "src/lex.c"
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy35;
	default:	goto yy37;
	}
yy37:
	id = yyt1;
	name = yyt2;
	sep = yyt2 - 1;
#line 109 "src/lex.re.c"
	{
            dst->type  = TOKEN_COMMAND;
            dst->begin = start;
            dst->end   = YYCURSOR;
            
            dst->data.cmd.id         = parse_int( id, sep );
            dst->data.cmd.name_begin = name;
            dst->data.cmd.name_end   = YYCURSOR;

            return YYCURSOR;
        }
#line 743 "src/lex.c"
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy12;
	default:	goto yy39;
	}
yy39:
#line 91 "src/lex.re.c"
	{
            dst->type         = TOKEN_BOOLEAN;
            dst->begin        = start;
            dst->end          = YYCURSOR;
            dst->data.boolean = 1;

            return YYCURSOR;
        }
#line 824 "src/lex.c"
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case ']':	goto yy41;
	default:	goto yy22;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':	goto yy42;
	default:	goto yy22;
	}
yy42:
	++YYCURSOR;
#line 69 "src/lex.re.c"
	{ dst->type = TOKEN_EOL;       return YYCURSOR; }
#line 841 "src/lex.c"
}
#line 128 "src/lex.re.c"

}
